function [K_alm,maxError,meanError]=DenHaanTest(p,m,s)
%---------------------------------------------------------------------------------------------------------------------------
% This function computes the test proposed in DenHaan (2008). It consists
% in a comparison between time series of capital generated by the nonstrochastic
% simulation and by the estimated ALM. I compute the maximum and average
% distance between both series as well. 
%---------------------------------------------------------------------------------------------------------------------------
T=p.end0-p.init0;
K_alm=zeros(T,1);  
K_alm(1)=s.K_ts(p.init0);                               
for t=1:T 
   if m.Zshock(t)==1
      K_alm(t+1)=exp(s.B(1)+s.B(2)*log(K_alm(t)));
   else
      K_alm(t+1)=exp(s.B(3)+s.B(4)*log(K_alm(t)));
   end
end
Error=abs(s.K_ts(p.init0:p.end0)-K_alm);
maxError=max(Error);
meanError=mean(Error);
%---------------------------------------------------------------------------------------------------------------------------