function o=estimationoptw(p,d,r)
%---------------------------------------------------------------------------------------------------------------------------
% This function estimates parameters of the Gamma distribution by GMM. I
% proceed in two steps. In the first one, I run a global search of
% parameters that minimize the objective criteria. Then, I use a built-in
% optimizer from Matlab to obtain finer results. With this two-steps
% algorithm I hope to avoid any problem generated by local minimums. 
%---------------------------------------------------------------------------------------------------------------------------
%% First step: global search
%---------------------------------------------------------------------------------------------------------------------------
P=linspace(p.Pmin,p.Pmax,p.nn);
lambda=linspace(p.lambdamin,p.lambdamax,p.nn);
J=zeros(p.nn,p.nn);
if p.usedmom==2
    o.param1=zeros(p.R,2);
    o.val1=zeros(p.R,1);
    o.wopt=zeros(p.usedmom,p.usedmom,p.R);
    for ii=1:p.R
        Mo(1)=p.comb(ii,1);
        Mo(2)=p.comb(ii,2);
        o.wopt(:,:,ii)=inv(phifun(d.y,Mo,r.param2(ii,:),p.usedmom));
        for id1=1:p.nn
            for id2=1:p.nn
                param(1)=P(id1);
                param(2)=lambda(id2);
                J(id1,id2)=objcrit(d.y,Mo,param,o.wopt(:,:,ii),p.usedmom);
            end
        end
        [i1,i2]=find(J==min(J(:)));
        o.param1(ii,:)=[P(i1) lambda(i2)];
        o.val1(ii,1)=J(i1,i2);
    end
elseif p.usedmom==4
    Mo=zeros(1,2);
    o.wopt=inv(phifun(d.y,Mo,r.param2,p.usedmom));
    for id1=1:p.nn
        for id2=1:p.nn
            param(1)=P(id1);
            param(2)=lambda(id2);
            J(id1,id2)=objcrit(d.y,Mo,param,o.wopt,p.usedmom);
        end
    end
    [i1,i2]=find(J==min(J(:)));
    o.param1=[P(i1) lambda(i2)];
    o.val1=J(i1,i2);
end
%---------------------------------------------------------------------------------------------------------------------------
%% Second step: minimizer
%---------------------------------------------------------------------------------------------------------------------------
if p.usedmom==2
    o.param2=zeros(p.R,2);
    o.val2=zeros(p.R,1);
    for ii=1:p.R
        Mo(1)=p.comb(ii,1);
        Mo(2)=p.comb(ii,2);
        o.wopt(:,:,ii)=inv(phifun(d.y,Mo,r.param2(ii,:),p.usedmom));
        fun=@(param) objcrit(d.y,Mo,param,o.wopt(:,:,ii),p.usedmom);
        if p.algo==1
            options=optimset('Display','off','TolFun',p.tol,'MaxIter',p.maxiter);
            [o.param2(ii,:),o.val2(ii,1)]=fminsearch(fun,o.param1(ii,:),options);
        elseif p.algo==2
            options = optimoptions('fminunc','Display','off','OptimalityTolerance',p.tol,...
                'MaxIterations',p.maxiter);
            [o.param2(ii,:),o.val2(ii,1)]=fminunc(fun,o.param1(ii,:),options);
        elseif p.algo==3
            options=optimset('Display','off','TolFun',p.tol,'MaxIter',p.maxiter);
            [o.param2(ii,:),o.val2(ii,1)]=fmincon(fun,o.param1(ii,:),[],[],[],[],[p.Pmin p.lambdamin],...
                [p.Pmax p.lambdamax],[],options);
        elseif p.algo==4
            options = optimoptions('patternsearch','Display','off','FunctionTolerance',p.tol,...
                'MaxIterations',p.maxiter);
            [o.param2(ii,:),o.val2(ii,1)]=patternsearch(fun,o.param1(ii,:),[],[],[],[],...
                [p.Pmin p.lambdamin],[p.Pmax p.lambdamax],[],options);
        end
    end
elseif p.usedmom==4
    Mo=zeros(1,2);
    o.wopt=inv(phifun(d.y,Mo,r.param2,p.usedmom));
    fun=@(param) objcrit(d.y,Mo,param,o.wopt,p.usedmom);
    if p.algo==1
        options=optimset('Display','off','TolFun',p.tol,'MaxIter',p.maxiter);
        [o.param2,o.val2]=fminsearch(fun,o.param1,options);
    elseif p.algo==2
        options = optimoptions('fminunc','Display','off','OptimalityTolerance',p.tol,...
            'MaxIterations',p.maxiter);
        [o.param2,o.val2]=fminunc(fun,o.param1,options);
    elseif p.algo==3
        options=optimset('Display','off','TolFun',p.tol,'MaxIter',p.maxiter);
        [o.param2,o.val2]=fmincon(fun,o.param1,[],[],[],[],[p.Pmin p.lambdamin],...
            [p.Pmax p.lambdamax],[],options);
    elseif p.algo==4
        options = optimoptions('patternsearch','Display','off','FunctionTolerance',p.tol,...
            'MaxIterations',p.maxiter);
        [o.param2,o.val2]=patternsearch(fun,o.param1,[],[],[],[],...
            [p.Pmin p.lambdamin],[p.Pmax p.lambdamax],[],options);
    end
end
%---------------------------------------------------------------------------------------------------------------------------